FROM node:20

RUN apt-get update && apt-get install -y python3 python3-pip

COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

RUN npm run build
CMD ["npm", "run", "start:prod"]
